[workspace]
authors = ["Jack Myers <jackhmyers97@gmail.com>"]
channels = ["conda-forge"]
name = "optimization-scenarios"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["env.sh"]

[dependencies]
python = ">=3.14.4,<3.15"
ollama-python = ">=0.6.1,<0.7"
pip = ">=26.0.1,<27"

[pypi-dependencies]
dspy = ">=3.2.0, <4"
